# All scripts are run inside this docker container
# This is mostly applicable for installer scripts, which can actually access the filesystem of the container
FROM --platform=linux/arm/v7 arm32v7/ubuntu
RUN apt-get update && apt-get install -y imagemagick
